    - name: Create VPC Public Subnet1
      ec2_vpc_subnet:
         state: present
         resource_tags: '{"Name":"{{ prefix }}_subnet_public_0"}'
         vpc_id: "{{ vpc.vpc_id }}"
         az: "{{ az0 }}"
         cidr: "{{ pub_subnet_cidr1 }}" 
      register: public1

    - name: Create VPC Public Subnet2
      ec2_vpc_subnet:
         state: present
         resource_tags: '{"Name":"{{ prefix }}_subnet_public_1"}'
         vpc_id: "{{ vpc.vpc_id }}"
         az: "{{ az1 }}"
         cidr: "{{ pub_subnet_cidr2 }}"
      register: public2

    - name: Create Public Subnet Route Table
      ec2_vpc_route_table:
         vpc_id: "{{ vpc.vpc_id }}"
         region: "{{ region }}"
         tags:
           Name: Public Subnet
         subnets:
           - "{{ public1.subnet.id }}"
           - "{{ public2.subnet.id }}"
         routes:
           - dest: 0.0.0.0/0
             gateway_id: "{{ igw.gateway_id }}"
