    - name: Create VPC Private Subnet1
      ec2_vpc_subnet:
         state: present
         resource_tags: '{"Name":"{{ prefix }}_subnet_private_0"}'
         vpc_id: "{{ vpc.vpc_id }}"
         az: "{{ az0 }}"
         cidr: "{{ priv_subnet_cidr1 }}"
      register: private1

    - name: Create VPC Private Subnet2
      ec2_vpc_subnet:
         state: present
         resource_tags: '{"Name":"{{ prefix }}_subnet_private_1"}'
         vpc_id: "{{ vpc.vpc_id }}"
         az: "{{ az1 }}"
         cidr: "{{ priv_subnet_cidr2 }}"
      register: private2

    - name: Create Private Subnet Route Table
      ec2_vpc_route_table:
         vpc_id: "{{ vpc.vpc_id }}"
         region: "{{ region }}"
         tags:
           Name: Private Subnet
         subnets:
           - "{{ private1.subnet.id }}"
           - "{{ private2.subnet.id }}"
         routes:
           - dest: 0.0.0.0/0
             instance_id: "{{ item.id }}"
      with_items: ec2_nat.instances
