    - name: Provisioning ELB
      local_action:
         module: ec2_elb_lb
         name: "{{ lb_name }}"
         state: present
         security_group_ids: "{{ elb_sg.group_id }}"
         subnets:
           - "{{ public1.subnet.id }}"
           - "{{ public2.subnet.id }}"
         listeners:
            - protocol: http
              load_balancer_port: 80
              instance_port: "{{ port }}"
         health_check:
            ping_protocol: tcp
            ping_port: "{{ port }}" 
            response_timeout: 2 
            interval: 10
            unhealthy_threshold: 2
            healthy_threshold: 3

    - name: Add Instance to Existing ELB
      ec2_elb:
        instance_id={{ ec2_nginx.instances[0].id }}
        ec2_elbs={{ lb_name }}
        state=present
        wait=no
      ignore_errors: true

