    - rds_subnet_group:
        state: present
        name: ansible-db-subnet
        description: db subnet
        subnets:
          - "{{ private1.subnet.id }}"
          - "{{ private2.subnet.id }}"

    -  rds:
        command: create
        instance_name: "{{ dbinstancename }}"
        db_engine: MySQL
        engine_version: "{{ dbengineversion }}"
        size: 10
        instance_type: "{{ dbinstancetype }}"
        multi_zone: no
        publicly_accessible: no
        subnet : ansible-db-subnet
        vpc_security_groups: "{{ db_sg.group_id }}"
        zone: "{{ az1 }}"
        region: "{{ region }}"
        username: "{{ dbusername }}"
        password: "{{ dbpassword }}"
        tags:
          Environment: ansible
