    - name: Launch nginx instance
      ec2:
         key_name: "{{ key }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         region: "{{ region }}"
         group_id: "{{ web_sg.group_id }}"
         vpc_subnet_id: "{{ private1.subnet.id }}"
         instance_tags:
            Name: "{{ prefix }}_nginx"
         wait: yes
      register: ec2_nginx

    - debug: var=ec2_nginx
     
