    - name: Launch NAT instance
      ec2:
         key_name: "{{ key }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         region: "{{ region }}"
         group_id: "{{ nat_sg.group_id }}"
         vpc_subnet_id: "{{ public1.subnet.id }}"
         instance_tags:
            Name: "{{ prefix }}_nat"
         assign_public_ip: yes
         source_dest_check: no
         wait: yes
      register: ec2_nat
  
    - debug: var=ec2_nat
